### ISSUE TITLE
ikonların input'lar ile birlikte hareket etmemesi

### ISSUE THREAD

**Issue by alper-batioglu** [STechQ/IDE-Design#1]
ikonların bir şeyin üzerine çıkmasını full absolute ve sayfa çapında left top gibi yerleştirmek yerine
<img width="172" alt="image" src="https://user-images.githubusercontent.com/26070511/165962524-f5737781-a977-4f45-a633-bfb3e01f5870.png">
parent'a relative verirsen, onunla birlikte hareket ederler.
<img width="170" alt="image" src="https://user-images.githubusercontent.com/26070511/165962644-e8dc935a-6959-431d-b982-0104b0127a9b.png">

**Comment by akalaycs** [comment]
Başta çok aynı olmasına dikkat ediyorum. Pdf teki css leri fazla bire bir takip etmişim hiç bakmadan. Düzelttim hepsini. Teşekkürler :)
